permissions:
  contents: write

name: Generate Datas

on:
  schedule: # executa a cada 12 horas
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Atualizar GitHub Snake
    runs-on: ubuntu-latest
    steps:
      # Gera a animação da Snake
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: GanNingPC
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Publica no branch output
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
